// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/account.dart';
import 'api/attachment.dart';
import 'api/chat.dart';
import 'api/config.dart';
import 'api/friends.dart';
import 'api/global_chat.dart';
import 'api/groups.dart';
import 'api/invites.dart';
import 'api/keys.dart';
import 'api/link_preview.dart';
import 'api/ratchet.dart';
import 'api/relay.dart';
import 'api/sync.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<AttachmentUploadEvent>
  dco_decode_StreamSink_attachment_upload_event_Sse(dynamic raw);

  @protected
  RustStreamSink<FriendEvent> dco_decode_StreamSink_friend_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<GlobalChannelMessage>
  dco_decode_StreamSink_global_channel_message_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Account dco_decode_account(dynamic raw);

  @protected
  AppConfig dco_decode_app_config(dynamic raw);

  @protected
  AttachmentUploadEvent dco_decode_attachment_upload_event(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Account dco_decode_box_autoadd_account(dynamic raw);

  @protected
  AppConfig dco_decode_box_autoadd_app_config(dynamic raw);

  @protected
  ChatAttachment dco_decode_box_autoadd_chat_attachment(dynamic raw);

  @protected
  GlobalChannel dco_decode_box_autoadd_global_channel(dynamic raw);

  @protected
  GroupChatAttachment dco_decode_box_autoadd_group_chat_attachment(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  Invite dco_decode_box_autoadd_invite(dynamic raw);

  @protected
  RemoteAccount dco_decode_box_autoadd_remote_account(dynamic raw);

  @protected
  RemoteAvatar dco_decode_box_autoadd_remote_avatar(dynamic raw);

  @protected
  RemoteFriends dco_decode_box_autoadd_remote_friends(dynamic raw);

  @protected
  RemoteRelays dco_decode_box_autoadd_remote_relays(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ChatAttachment dco_decode_chat_attachment(dynamic raw);

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Friend dco_decode_friend(dynamic raw);

  @protected
  FriendBackupEntry dco_decode_friend_backup_entry(dynamic raw);

  @protected
  FriendEvent dco_decode_friend_event(dynamic raw);

  @protected
  GlobalChannel dco_decode_global_channel(dynamic raw);

  @protected
  GlobalChannelMessage dco_decode_global_channel_message(dynamic raw);

  @protected
  GlobalChatProfile dco_decode_global_chat_profile(dynamic raw);

  @protected
  Group dco_decode_group(dynamic raw);

  @protected
  GroupChatAttachment dco_decode_group_chat_attachment(dynamic raw);

  @protected
  GroupChatMessage dco_decode_group_chat_message(dynamic raw);

  @protected
  GroupMember dco_decode_group_member(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Invite dco_decode_invite(dynamic raw);

  @protected
  InviteQrPayload dco_decode_invite_qr_payload(dynamic raw);

  @protected
  LinkPreview dco_decode_link_preview(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<bool> dco_decode_list_bool(dynamic raw);

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw);

  @protected
  List<Friend> dco_decode_list_friend(dynamic raw);

  @protected
  List<FriendBackupEntry> dco_decode_list_friend_backup_entry(dynamic raw);

  @protected
  List<GlobalChannel> dco_decode_list_global_channel(dynamic raw);

  @protected
  List<GlobalChannelMessage> dco_decode_list_global_channel_message(
    dynamic raw,
  );

  @protected
  List<GlobalChatProfile> dco_decode_list_global_chat_profile(dynamic raw);

  @protected
  List<Group> dco_decode_list_group(dynamic raw);

  @protected
  List<GroupChatMessage> dco_decode_list_group_chat_message(dynamic raw);

  @protected
  List<GroupMember> dco_decode_list_group_member(dynamic raw);

  @protected
  List<Invite> dco_decode_list_invite(dynamic raw);

  @protected
  List<PendingFriendRequest> dco_decode_list_pending_friend_request(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PriorIdentity> dco_decode_list_prior_identity(dynamic raw);

  @protected
  List<RatchetChatMessage> dco_decode_list_ratchet_chat_message(dynamic raw);

  @protected
  List<UnreadCount> dco_decode_list_unread_count(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Account? dco_decode_opt_box_autoadd_account(dynamic raw);

  @protected
  ChatAttachment? dco_decode_opt_box_autoadd_chat_attachment(dynamic raw);

  @protected
  GroupChatAttachment? dco_decode_opt_box_autoadd_group_chat_attachment(
    dynamic raw,
  );

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  RemoteAccount? dco_decode_opt_box_autoadd_remote_account(dynamic raw);

  @protected
  RemoteAvatar? dco_decode_opt_box_autoadd_remote_avatar(dynamic raw);

  @protected
  RemoteFriends? dco_decode_opt_box_autoadd_remote_friends(dynamic raw);

  @protected
  RemoteRelays? dco_decode_opt_box_autoadd_remote_relays(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PendingFriendRequest dco_decode_pending_friend_request(dynamic raw);

  @protected
  PriorIdentity dco_decode_prior_identity(dynamic raw);

  @protected
  RatchetChatMessage dco_decode_ratchet_chat_message(dynamic raw);

  @protected
  RelayList dco_decode_relay_list(dynamic raw);

  @protected
  RemoteAccount dco_decode_remote_account(dynamic raw);

  @protected
  RemoteAvatar dco_decode_remote_avatar(dynamic raw);

  @protected
  RemoteFriends dco_decode_remote_friends(dynamic raw);

  @protected
  RemoteRelays dco_decode_remote_relays(dynamic raw);

  @protected
  SyncState dco_decode_sync_state(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnreadCount dco_decode_unread_count(dynamic raw);

  @protected
  UploadServerList dco_decode_upload_server_list(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<AttachmentUploadEvent>
  sse_decode_StreamSink_attachment_upload_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<FriendEvent> sse_decode_StreamSink_friend_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<GlobalChannelMessage>
  sse_decode_StreamSink_global_channel_message_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Account sse_decode_account(SseDeserializer deserializer);

  @protected
  AppConfig sse_decode_app_config(SseDeserializer deserializer);

  @protected
  AttachmentUploadEvent sse_decode_attachment_upload_event(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Account sse_decode_box_autoadd_account(SseDeserializer deserializer);

  @protected
  AppConfig sse_decode_box_autoadd_app_config(SseDeserializer deserializer);

  @protected
  ChatAttachment sse_decode_box_autoadd_chat_attachment(
    SseDeserializer deserializer,
  );

  @protected
  GlobalChannel sse_decode_box_autoadd_global_channel(
    SseDeserializer deserializer,
  );

  @protected
  GroupChatAttachment sse_decode_box_autoadd_group_chat_attachment(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Invite sse_decode_box_autoadd_invite(SseDeserializer deserializer);

  @protected
  RemoteAccount sse_decode_box_autoadd_remote_account(
    SseDeserializer deserializer,
  );

  @protected
  RemoteAvatar sse_decode_box_autoadd_remote_avatar(
    SseDeserializer deserializer,
  );

  @protected
  RemoteFriends sse_decode_box_autoadd_remote_friends(
    SseDeserializer deserializer,
  );

  @protected
  RemoteRelays sse_decode_box_autoadd_remote_relays(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ChatAttachment sse_decode_chat_attachment(SseDeserializer deserializer);

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Friend sse_decode_friend(SseDeserializer deserializer);

  @protected
  FriendBackupEntry sse_decode_friend_backup_entry(
    SseDeserializer deserializer,
  );

  @protected
  FriendEvent sse_decode_friend_event(SseDeserializer deserializer);

  @protected
  GlobalChannel sse_decode_global_channel(SseDeserializer deserializer);

  @protected
  GlobalChannelMessage sse_decode_global_channel_message(
    SseDeserializer deserializer,
  );

  @protected
  GlobalChatProfile sse_decode_global_chat_profile(
    SseDeserializer deserializer,
  );

  @protected
  Group sse_decode_group(SseDeserializer deserializer);

  @protected
  GroupChatAttachment sse_decode_group_chat_attachment(
    SseDeserializer deserializer,
  );

  @protected
  GroupChatMessage sse_decode_group_chat_message(SseDeserializer deserializer);

  @protected
  GroupMember sse_decode_group_member(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Invite sse_decode_invite(SseDeserializer deserializer);

  @protected
  InviteQrPayload sse_decode_invite_qr_payload(SseDeserializer deserializer);

  @protected
  LinkPreview sse_decode_link_preview(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer);

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer);

  @protected
  List<Friend> sse_decode_list_friend(SseDeserializer deserializer);

  @protected
  List<FriendBackupEntry> sse_decode_list_friend_backup_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<GlobalChannel> sse_decode_list_global_channel(
    SseDeserializer deserializer,
  );

  @protected
  List<GlobalChannelMessage> sse_decode_list_global_channel_message(
    SseDeserializer deserializer,
  );

  @protected
  List<GlobalChatProfile> sse_decode_list_global_chat_profile(
    SseDeserializer deserializer,
  );

  @protected
  List<Group> sse_decode_list_group(SseDeserializer deserializer);

  @protected
  List<GroupChatMessage> sse_decode_list_group_chat_message(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupMember> sse_decode_list_group_member(SseDeserializer deserializer);

  @protected
  List<Invite> sse_decode_list_invite(SseDeserializer deserializer);

  @protected
  List<PendingFriendRequest> sse_decode_list_pending_friend_request(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PriorIdentity> sse_decode_list_prior_identity(
    SseDeserializer deserializer,
  );

  @protected
  List<RatchetChatMessage> sse_decode_list_ratchet_chat_message(
    SseDeserializer deserializer,
  );

  @protected
  List<UnreadCount> sse_decode_list_unread_count(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Account? sse_decode_opt_box_autoadd_account(SseDeserializer deserializer);

  @protected
  ChatAttachment? sse_decode_opt_box_autoadd_chat_attachment(
    SseDeserializer deserializer,
  );

  @protected
  GroupChatAttachment? sse_decode_opt_box_autoadd_group_chat_attachment(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RemoteAccount? sse_decode_opt_box_autoadd_remote_account(
    SseDeserializer deserializer,
  );

  @protected
  RemoteAvatar? sse_decode_opt_box_autoadd_remote_avatar(
    SseDeserializer deserializer,
  );

  @protected
  RemoteFriends? sse_decode_opt_box_autoadd_remote_friends(
    SseDeserializer deserializer,
  );

  @protected
  RemoteRelays? sse_decode_opt_box_autoadd_remote_relays(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PendingFriendRequest sse_decode_pending_friend_request(
    SseDeserializer deserializer,
  );

  @protected
  PriorIdentity sse_decode_prior_identity(SseDeserializer deserializer);

  @protected
  RatchetChatMessage sse_decode_ratchet_chat_message(
    SseDeserializer deserializer,
  );

  @protected
  RelayList sse_decode_relay_list(SseDeserializer deserializer);

  @protected
  RemoteAccount sse_decode_remote_account(SseDeserializer deserializer);

  @protected
  RemoteAvatar sse_decode_remote_avatar(SseDeserializer deserializer);

  @protected
  RemoteFriends sse_decode_remote_friends(SseDeserializer deserializer);

  @protected
  RemoteRelays sse_decode_remote_relays(SseDeserializer deserializer);

  @protected
  SyncState sse_decode_sync_state(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnreadCount sse_decode_unread_count(SseDeserializer deserializer);

  @protected
  UploadServerList sse_decode_upload_server_list(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_attachment_upload_event_Sse(
    RustStreamSink<AttachmentUploadEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_friend_event_Sse(
    RustStreamSink<FriendEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_global_channel_message_Sse(
    RustStreamSink<GlobalChannelMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account(Account self, SseSerializer serializer);

  @protected
  void sse_encode_app_config(AppConfig self, SseSerializer serializer);

  @protected
  void sse_encode_attachment_upload_event(
    AttachmentUploadEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_account(Account self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_config(
    AppConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_chat_attachment(
    ChatAttachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_global_channel(
    GlobalChannel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_group_chat_attachment(
    GroupChatAttachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_invite(Invite self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_remote_account(
    RemoteAccount self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_remote_avatar(
    RemoteAvatar self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_remote_friends(
    RemoteFriends self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_remote_relays(
    RemoteRelays self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_chat_attachment(
    ChatAttachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_friend(Friend self, SseSerializer serializer);

  @protected
  void sse_encode_friend_backup_entry(
    FriendBackupEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_friend_event(FriendEvent self, SseSerializer serializer);

  @protected
  void sse_encode_global_channel(GlobalChannel self, SseSerializer serializer);

  @protected
  void sse_encode_global_channel_message(
    GlobalChannelMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_global_chat_profile(
    GlobalChatProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group(Group self, SseSerializer serializer);

  @protected
  void sse_encode_group_chat_attachment(
    GroupChatAttachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_chat_message(
    GroupChatMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_member(GroupMember self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_invite(Invite self, SseSerializer serializer);

  @protected
  void sse_encode_invite_qr_payload(
    InviteQrPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_link_preview(LinkPreview self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chat_message(
    List<ChatMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_friend(List<Friend> self, SseSerializer serializer);

  @protected
  void sse_encode_list_friend_backup_entry(
    List<FriendBackupEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_global_channel(
    List<GlobalChannel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_global_channel_message(
    List<GlobalChannelMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_global_chat_profile(
    List<GlobalChatProfile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group(List<Group> self, SseSerializer serializer);

  @protected
  void sse_encode_list_group_chat_message(
    List<GroupChatMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_member(
    List<GroupMember> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_invite(List<Invite> self, SseSerializer serializer);

  @protected
  void sse_encode_list_pending_friend_request(
    List<PendingFriendRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prior_identity(
    List<PriorIdentity> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ratchet_chat_message(
    List<RatchetChatMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_unread_count(
    List<UnreadCount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_account(
    Account? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_chat_attachment(
    ChatAttachment? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_group_chat_attachment(
    GroupChatAttachment? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_remote_account(
    RemoteAccount? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_remote_avatar(
    RemoteAvatar? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_remote_friends(
    RemoteFriends? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_remote_relays(
    RemoteRelays? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_pending_friend_request(
    PendingFriendRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_prior_identity(PriorIdentity self, SseSerializer serializer);

  @protected
  void sse_encode_ratchet_chat_message(
    RatchetChatMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_relay_list(RelayList self, SseSerializer serializer);

  @protected
  void sse_encode_remote_account(RemoteAccount self, SseSerializer serializer);

  @protected
  void sse_encode_remote_avatar(RemoteAvatar self, SseSerializer serializer);

  @protected
  void sse_encode_remote_friends(RemoteFriends self, SseSerializer serializer);

  @protected
  void sse_encode_remote_relays(RemoteRelays self, SseSerializer serializer);

  @protected
  void sse_encode_sync_state(SyncState self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unread_count(UnreadCount self, SseSerializer serializer);

  @protected
  void sse_encode_upload_server_list(
    UploadServerList self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
