// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `account_path`, `now`, `write_avatar_bytes`

/// Copies a freshly-picked avatar image into permanent per-account storage.
/// Returns `None` if `picked_path` couldn't be read.
Future<String?> saveAccountAvatar({
  required String storageDir,
  required String pickedPath,
}) => RustLib.instance.api.crateApiAccountSaveAccountAvatar(
  storageDir: storageDir,
  pickedPath: pickedPath,
);

/// Encrypts the avatar at `avatar_path` and uploads it to the configured
/// Blossom server, returning a self-contained encrypted link (see
/// `attachment::upload_encrypted_link`). Call once whenever the avatar
/// actually changes — the result is meant to be persisted via `save_account`
/// (`avatar_link`) and then reused as-is by every friend request/accept/
/// profile-update/self-backup, rather than re-uploading a fresh copy of the
/// same bytes on each one. Signed with a dedicated per-device key
/// (`keys::derive_avatar_upload_keys`) never shared with anyone — see that
/// function's doc for why.
/// `previous_avatar_link` (the value being replaced, if any) is best-effort
/// deleted from the Blossom server after the new upload succeeds, so
/// replacing an avatar repeatedly doesn't leave every past encrypted copy
/// sitting there forever — failures (server doesn't support delete, offline,
/// already gone) are silently ignored since cleanup isn't essential to the
/// replace itself succeeding.
Future<String> uploadAccountAvatarLink({
  required String mnemonic,
  required String storageDir,
  required String avatarPath,
  String? previousAvatarLink,
}) => RustLib.instance.api.crateApiAccountUploadAccountAvatarLink(
  mnemonic: mnemonic,
  storageDir: storageDir,
  avatarPath: avatarPath,
  previousAvatarLink: previousAvatarLink,
);

/// Deletes this account's currently-uploaded avatar blob from the Blossom
/// server — called on account deletion, since nothing will ever reference
/// it again once the local account is wiped. Best-effort: the caller should
/// ignore failures (offline, server doesn't support delete, already gone).
Future<void> deleteAccountAvatarBlob({
  required String mnemonic,
  required String avatarLink,
}) => RustLib.instance.api.crateApiAccountDeleteAccountAvatarBlob(
  mnemonic: mnemonic,
  avatarLink: avatarLink,
);

/// Downloads and decrypts an encrypted avatar link (from a friend's
/// [FriendPayload]-style exchange or this account's own relay-hosted
/// backup) and caches the plaintext bytes locally, the same
/// content-hash-suffixed way as a locally-picked avatar.
Future<String?> saveAccountAvatarLink({
  required String storageDir,
  required String avatarLink,
}) => RustLib.instance.api.crateApiAccountSaveAccountAvatarLink(
  storageDir: storageDir,
  avatarLink: avatarLink,
);

/// Saves the account as JSON under `storage_dir`, stamping `updated_at` with
/// the current time. `storage_dir` must already exist (e.g. the app's
/// documents directory, resolved on the Dart side via path_provider).
Future<void> saveAccount({
  required String storageDir,
  required String displayName,
  required String statusMessage,
  String? avatarPath,
  String? avatarLink,
}) => RustLib.instance.api.crateApiAccountSaveAccount(
  storageDir: storageDir,
  displayName: displayName,
  statusMessage: statusMessage,
  avatarPath: avatarPath,
  avatarLink: avatarLink,
);

/// Saves the account as JSON under `storage_dir` with an explicit
/// `updated_at`, used when overwriting the local copy with a newer backup
/// pulled from a relay (so the local timestamp matches the relay's).
Future<void> saveAccountWithTimestamp({
  required String storageDir,
  required String displayName,
  required String statusMessage,
  String? avatarPath,
  String? avatarLink,
  required PlatformInt64 updatedAt,
}) => RustLib.instance.api.crateApiAccountSaveAccountWithTimestamp(
  storageDir: storageDir,
  displayName: displayName,
  statusMessage: statusMessage,
  avatarPath: avatarPath,
  avatarLink: avatarLink,
  updatedAt: updatedAt,
);

/// Loads a previously saved account, or `None` if none has been saved yet.
Future<Account?> loadAccount({required String storageDir}) =>
    RustLib.instance.api.crateApiAccountLoadAccount(storageDir: storageDir);

/// Local account identity: display info persisted per-device.
class Account {
  final String displayName;
  final String statusMessage;

  /// Absolute path to the avatar image file, if the user picked one.
  final String? avatarPath;

  /// A self-contained encrypted link (`<blossom-url>#<hex key+nonce>`,
  /// see `attachment::upload_encrypted_link`) for the same image
  /// `avatar_path` points to — computed once per avatar change (via
  /// [upload_account_avatar_link]) and reused for every friend
  /// request/accept/profile-update/self-backup instead of re-uploading a
  /// fresh (undeduplicatable — each upload uses a random key) copy of the
  /// same bytes every time one of those fires.
  final String? avatarLink;

  /// Unix timestamp (seconds) of the last local edit. Used to decide
  /// whether the local copy or the relay-synced backup is newer.
  final PlatformInt64 updatedAt;

  const Account({
    required this.displayName,
    required this.statusMessage,
    this.avatarPath,
    this.avatarLink,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^
      statusMessage.hashCode ^
      avatarPath.hashCode ^
      avatarLink.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Account &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          statusMessage == other.statusMessage &&
          avatarPath == other.avatarPath &&
          avatarLink == other.avatarLink &&
          updatedAt == other.updatedAt;
}
