// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blossom_auth_event`, `decrypt_attachment_bytes`, `default_upload_server_urls`, `download_ciphertext`, `encrypt_attachment_bytes`, `http_client`, `upload_and_send`, `upload_ciphertext`, `upload_plain_bytes`, `upload_server_path`, `upload_servers_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BlobDescriptor`, `UploadServerConfig`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

/// Dart-callable accessor for [default_upload_server_urls] — lets the
/// settings screen offer a "reset to defaults" action.
Future<List<String>> defaultUploadServers() =>
    RustLib.instance.api.crateApiAttachmentDefaultUploadServers();

/// Persists the full set of configured upload servers plus which one is the
/// default. `default_url` must be one of `urls`.
Future<void> saveUploadServers({
  required String storageDir,
  required List<String> urls,
  required String defaultUrl,
}) => RustLib.instance.api.crateApiAttachmentSaveUploadServers(
  storageDir: storageDir,
  urls: urls,
  defaultUrl: defaultUrl,
);

/// The saved server list, or the built-in defaults if none has been saved
/// yet. Falls back to migrating a legacy single-URL `upload_server.json`
/// (from before servers became a list) so an already-configured server
/// isn't silently forgotten on upgrade.
Future<UploadServerList> loadUploadServers({required String storageDir}) =>
    RustLib.instance.api.crateApiAttachmentLoadUploadServers(
      storageDir: storageDir,
    );

/// Checks whether `url` currently responds, for the settings screen's
/// online/offline indicator — mirrors [relay::check_relay_statuses], but
/// over plain HTTP(S) rather than a WebSocket handshake since Blossom
/// servers speak HTTP.
Future<bool> checkUploadServerStatus({required String url}) =>
    RustLib.instance.api.crateApiAttachmentCheckUploadServerStatus(url: url);

/// Encrypts `file_path`'s bytes to `friend_pubkey` (same per-contact key as
/// [chat::send_chat_message]) and uploads the ciphertext to the configured
/// Blossom server — streaming progress events (`done: false`) as the body
/// is sent — then sends a small JSON pointer (URL + hash + optional
/// caption + original filename/mime type) as a chat message the same way a
/// text message is sent — sealed, gift-wrapped to the friend, and
/// self-echoed to our own relays so it shows up on our other devices too.
/// Terminates the stream with one `done: true` event (`error` set on
/// failure) — fire-and-forget from Dart's side, like
/// [crate::api::sync::subscribe_friend_events].
Stream<AttachmentUploadEvent> sendChatAttachment({
  required String mnemonic,
  required String storageDir,
  required String friendPubkey,
  required String filePath,
  required String mimeType,
  String? caption,
  String? replyTo,
  String? serverOverride,
}) => RustLib.instance.api.crateApiAttachmentSendChatAttachment(
  mnemonic: mnemonic,
  storageDir: storageDir,
  friendPubkey: friendPubkey,
  filePath: filePath,
  mimeType: mimeType,
  caption: caption,
  replyTo: replyTo,
  serverOverride: serverOverride,
);

/// Downloads and decrypts the attachment on `message_id` (a message
/// previously decoded with a non-null `attachment` field), caching the
/// plaintext bytes under `storage_dir` so repeat views (or the sender's own
/// copy) don't re-download/re-decrypt every time. Returns the local file
/// path.
Future<String> downloadChatAttachment({
  required String mnemonic,
  required String storageDir,
  required String friendPubkey,
  required String messageId,
  required String url,
  required String encKey,
}) => RustLib.instance.api.crateApiAttachmentDownloadChatAttachment(
  mnemonic: mnemonic,
  storageDir: storageDir,
  friendPubkey: friendPubkey,
  messageId: messageId,
  url: url,
  encKey: encKey,
);

/// Progress/outcome events for [send_chat_attachment], streamed back so the
/// UI can show a real upload progress ring instead of a spinner. A plain
/// struct (rather than a Rust enum) so flutter_rust_bridge doesn't need the
/// `freezed` codegen package just for this one stream — Dart checks `done`/
/// `error` to distinguish a terminal event from a progress tick.
class AttachmentUploadEvent {
  /// Share of the (encrypted) body written so far, `0.0..=1.0`.
  final double fraction;
  final bool done;
  final String? error;

  const AttachmentUploadEvent({
    required this.fraction,
    required this.done,
    this.error,
  });

  @override
  int get hashCode => fraction.hashCode ^ done.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentUploadEvent &&
          runtimeType == other.runtimeType &&
          fraction == other.fraction &&
          done == other.done &&
          error == other.error;
}

/// The set of configured Blossom-compatible upload servers, mirroring
/// [relay::RelayList]'s shape. `default_url` is the one actually used by
/// [send_chat_attachment]/[download_chat_attachment] unless a specific
/// server is passed in (e.g. after a user picks a fallback from the
/// switch-server dialog) — always kept a member of `urls`.
class UploadServerList {
  final List<String> urls;
  final String defaultUrl;

  const UploadServerList({required this.urls, required this.defaultUrl});

  @override
  int get hashCode => urls.hashCode ^ defaultUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadServerList &&
          runtimeType == other.runtimeType &&
          urls == other.urls &&
          defaultUrl == other.defaultUrl;
}
