// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `channel_from_creation_event`, `client_tag`, `global_profile_marker_path`, `has_origilink_client_tag`, `profile_from_metadata_event`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChannelMetadataContent`, `ProfileMetadataContent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Creates a new public channel (NIP-28 kind 40), signed with this
/// account's dedicated Global Chat identity (see `keys::derive_global_chat_keys`)
/// rather than its core identity — a channel is public by nature and posts
/// to it shouldn't be linkable to the self-addressed account-backup events
/// published under the core key. Tagged as an Origilink channel (see module
/// doc). Returns the new channel's id.
Future<String> createChannel({
  required String mnemonic,
  required List<String> relayUrls,
  required String name,
  required String about,
}) => RustLib.instance.api.crateApiGlobalChatCreateChannel(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
  name: name,
  about: about,
);

/// Lists every public channel visible on `relay_urls`, most active first —
/// each result carries `is_origilink` (see module doc) so the Dart side can
/// filter the "Origilink channels only" vs. "all channels" toggle purely
/// client-side, without a fresh relay round-trip per toggle flip: the
/// underlying query here never depended on that flag to begin with, it was
/// only ever applied to the already-fetched results.
///
/// Sorting by raw channel-creation recency alone buries every channel with
/// real conversation under a constant stream of freshly-created spam
/// channels (public relays see many of these) — a channel from months ago
/// with real traffic would never make it into the (necessarily bounded)
/// creation-event page. So this pulls a batch of *recent messages* first
/// and uses how many reference each channel as an activity signal, then
/// resolves creation events for both the newest channels and whichever
/// channels that message sample surfaced (which may be much older),
/// finally ranking by message count with recency as the tiebreak.
Future<List<GlobalChannel>> listChannels({required List<String> relayUrls}) =>
    RustLib.instance.api.crateApiGlobalChatListChannels(relayUrls: relayUrls);

/// Loads up to a page of `channel_id`'s messages, across `relay_urls`.
/// `before` (when set) pages backward from that Unix timestamp instead of
/// from "now" — pass the oldest-currently-loaded message's `created_at` to
/// fetch the next page of history, mirroring `chat.rs`'s `load_older`
/// pattern so the channel timeline isn't hard-capped at one page forever.
Future<List<GlobalChannelMessage>> loadChannelMessages({
  required List<String> relayUrls,
  required String channelId,
  PlatformInt64? before,
}) => RustLib.instance.api.crateApiGlobalChatLoadChannelMessages(
  relayUrls: relayUrls,
  channelId: channelId,
  before: before,
);

/// Opens a live subscription on `channel_id` across `relay_urls`, streaming
/// new messages as they arrive for as long as the returned Dart stream is
/// listened to — mirrors `sync::subscribe_friend_events`'s "one task per
/// relay, forward into a shared sink" shape, but far simpler: no
/// resubscribe/backoff loop, since a channel subscription is cheap to just
/// re-open by calling this again (the Dart side does, via a fresh
/// `GlobalChatThreadScreen`/key). `since(now)` means this only ever
/// delivers messages newer than the moment it opened — the initial page
/// from [load_channel_messages] covers everything up to that point.
Stream<GlobalChannelMessage> subscribeChannelMessages({
  required List<String> relayUrls,
  required String channelId,
}) => RustLib.instance.api.crateApiGlobalChatSubscribeChannelMessages(
  relayUrls: relayUrls,
  channelId: channelId,
);

/// Loads NIP-01 profile metadata (kind 0) for `pubkeys`, across
/// `relay_urls`. Kind 0 is a "replaceable" event — a pubkey may have many
/// old copies floating around relays — so this keeps only the newest per
/// author. Pubkeys with no metadata found (never published one, or it's on
/// a relay outside `relay_urls`) simply don't appear in the result; callers
/// fall back to showing the raw pubkey for those.
Future<List<GlobalChatProfile>> loadProfiles({
  required List<String> relayUrls,
  required List<String> pubkeys,
}) => RustLib.instance.api.crateApiGlobalChatLoadProfiles(
  relayUrls: relayUrls,
  pubkeys: pubkeys,
);

/// Posts `content` to `channel_id`, signed with this account's dedicated
/// Global Chat identity (same reasoning as [create_channel]).
Future<void> sendChannelMessage({
  required String mnemonic,
  required List<String> relayUrls,
  required String channelId,
  required String content,
}) => RustLib.instance.api.crateApiGlobalChatSendChannelMessage(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
  channelId: channelId,
  content: content,
);

/// Dart-callable accessor for this account's dedicated Global Chat identity
/// pubkey (used to tell "my own message" apart from others' in the channel
/// timeline — mirrors how `account`/`chat` expose the account's own
/// identity, but scoped to the Global Chat key rather than the core one).
Future<String> globalChatIdentityPubkey({required String mnemonic}) => RustLib
    .instance
    .api
    .crateApiGlobalChatGlobalChatIdentityPubkey(mnemonic: mnemonic);

/// Whether this device has ever completed Global Profile setup (as opposed
/// to skipping it) — a plain local marker file rather than a relay query,
/// since the point is to gate the *local* redirect-to-setup UX, not to
/// verify a kind-0 event still exists on some relay. Deliberately not part
/// of `Account`/its backup: a fresh device restored from the seed phrase
/// should re-decide (or re-skip) Global Profile setup on its own, the same
/// way it re-decides relay settings, rather than silently inheriting
/// whatever the original device chose.
Future<bool> hasGlobalProfile({required String storageDir}) => RustLib
    .instance
    .api
    .crateApiGlobalChatHasGlobalProfile(storageDir: storageDir);

/// Publishes a NIP-01 profile (kind 0) for this account's dedicated Global
/// Chat identity — the display name/bio shown next to this account's
/// channel posts (see `keys::derive_global_chat_keys` for why this is a
/// separate identity from the core account). Marks Global Profile setup as
/// completed locally on success (see [has_global_profile]).
Future<void> publishGlobalProfile({
  required String mnemonic,
  required String storageDir,
  required List<String> relayUrls,
  required String name,
  required String about,
}) => RustLib.instance.api.crateApiGlobalChatPublishGlobalProfile(
  mnemonic: mnemonic,
  storageDir: storageDir,
  relayUrls: relayUrls,
  name: name,
  about: about,
);

/// A NIP-28 channel, as shown in the channel list.
class GlobalChannel {
  /// The channel's creation event id — its stable identifier.
  final String id;
  final String name;
  final String about;
  final String creatorPubkey;
  final PlatformInt64 createdAt;

  /// Whether the creation event carried Origilink's `client` tag.
  final bool isOrigilink;

  const GlobalChannel({
    required this.id,
    required this.name,
    required this.about,
    required this.creatorPubkey,
    required this.createdAt,
    required this.isOrigilink,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      about.hashCode ^
      creatorPubkey.hashCode ^
      createdAt.hashCode ^
      isOrigilink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlobalChannel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          about == other.about &&
          creatorPubkey == other.creatorPubkey &&
          createdAt == other.createdAt &&
          isOrigilink == other.isOrigilink;
}

/// A single message in a channel's timeline.
class GlobalChannelMessage {
  final String id;
  final String channelId;
  final String senderPubkey;
  final String content;
  final PlatformInt64 createdAt;

  const GlobalChannelMessage({
    required this.id,
    required this.channelId,
    required this.senderPubkey,
    required this.content,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      channelId.hashCode ^
      senderPubkey.hashCode ^
      content.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlobalChannelMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          channelId == other.channelId &&
          senderPubkey == other.senderPubkey &&
          content == other.content &&
          createdAt == other.createdAt;
}

class GlobalChatProfile {
  final String pubkey;
  final String? name;
  final String? picture;

  const GlobalChatProfile({required this.pubkey, this.name, this.picture});

  @override
  int get hashCode => pubkey.hashCode ^ name.hashCode ^ picture.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlobalChatProfile &&
          runtimeType == other.runtimeType &&
          pubkey == other.pubkey &&
          name == other.name &&
          picture == other.picture;
}
