// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_contact_keys`, `derive_global_chat_keys`, `derive_keys`, `derive_uid`

/// Generates a new 12-word BIP-39 seed phrase. The caller is responsible for
/// persisting it (e.g. via platform secure storage) — this function is pure
/// generation with no I/O.
Future<String> generateMnemonic() =>
    RustLib.instance.api.crateApiKeysGenerateMnemonic();

/// Validates that `mnemonic` is both a proper BIP-39 phrase and one that can
/// derive Nostr keys (NIP-06).
Future<void> validateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiKeysValidateMnemonic(mnemonic: mnemonic);

/// Dart-callable wrapper around [derive_uid] — lets the profile screen show
/// the account's own UID (e.g. for the user to compare against a friend's).
Future<String> getAccountUid({required String mnemonic}) =>
    RustLib.instance.api.crateApiKeysGetAccountUid(mnemonic: mnemonic);
