// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `channel_from_creation_event`, `client_tag`, `has_origilink_client_tag`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChannelMetadataContent`

/// Creates a new public channel (NIP-28 kind 40), signed with this
/// account's core identity (the same one used for the relay-hosted account
/// backup — see `keys::derive_keys`), since a channel is public by nature
/// and doesn't need a per-relationship unlinkable key. Tagged as an
/// Origilink channel (see module doc). Returns the new channel's id.
Future<String> createChannel({
  required String mnemonic,
  required List<String> relayUrls,
  required String name,
  required String about,
}) => RustLib.instance.api.crateApiPublicChatCreateChannel(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
  name: name,
  about: about,
);

/// Lists public channels visible on `relay_urls`. When `origilink_only` is
/// true (the default list view), only channels tagged by this app are
/// returned; otherwise every NIP-28 channel on those relays is included —
/// see module doc for why this is a UI filter, not a protocol boundary.
Future<List<PublicChannel>> listChannels({
  required List<String> relayUrls,
  required bool origilinkOnly,
}) => RustLib.instance.api.crateApiPublicChatListChannels(
  relayUrls: relayUrls,
  origilinkOnly: origilinkOnly,
);

/// Loads the most recent messages in `channel_id`, across `relay_urls`.
Future<List<PublicChannelMessage>> loadChannelMessages({
  required List<String> relayUrls,
  required String channelId,
}) => RustLib.instance.api.crateApiPublicChatLoadChannelMessages(
  relayUrls: relayUrls,
  channelId: channelId,
);

/// Posts `content` to `channel_id`, signed with this account's core
/// identity (same reasoning as [create_channel]).
Future<void> sendChannelMessage({
  required String mnemonic,
  required List<String> relayUrls,
  required String channelId,
  required String content,
}) => RustLib.instance.api.crateApiPublicChatSendChannelMessage(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
  channelId: channelId,
  content: content,
);

/// Dart-callable accessor for this account's public identity pubkey (used
/// to tell "my own message" apart from others' in the channel timeline —
/// mirrors how `account`/`chat` expose the account's own identity).
Future<String> publicChatIdentityPubkey({required String mnemonic}) => RustLib
    .instance
    .api
    .crateApiPublicChatPublicChatIdentityPubkey(mnemonic: mnemonic);

/// A NIP-28 channel, as shown in the channel list.
class PublicChannel {
  /// The channel's creation event id — its stable identifier.
  final String id;
  final String name;
  final String about;
  final String creatorPubkey;
  final PlatformInt64 createdAt;

  /// Whether the creation event carried Origilink's `client` tag.
  final bool isOrigilink;

  const PublicChannel({
    required this.id,
    required this.name,
    required this.about,
    required this.creatorPubkey,
    required this.createdAt,
    required this.isOrigilink,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      about.hashCode ^
      creatorPubkey.hashCode ^
      createdAt.hashCode ^
      isOrigilink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PublicChannel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          about == other.about &&
          creatorPubkey == other.creatorPubkey &&
          createdAt == other.createdAt &&
          isOrigilink == other.isOrigilink;
}

/// A single message in a channel's timeline.
class PublicChannelMessage {
  final String id;
  final String channelId;
  final String senderPubkey;
  final String content;
  final PlatformInt64 createdAt;

  const PublicChannelMessage({
    required this.id,
    required this.channelId,
    required this.senderPubkey,
    required this.content,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      channelId.hashCode ^
      senderPubkey.hashCode ^
      content.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PublicChannelMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          channelId == other.channelId &&
          senderPubkey == other.senderPubkey &&
          content == other.content &&
          createdAt == other.createdAt;
}
