// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bump_local_watermark`, `encrypt_self`, `fetch_latest_backup_event`, `listen_for_account_sync`, `listen_for_friend_events`, `load_sync_state`, `mark_event_seen`, `now`, `publish_account_incoming_backup_async`, `publish_account_incoming_backup`, `publish_account_outgoing_backup_async`, `publish_account_outgoing_backup`, `publish_backup_event_async`, `publish_backup_event`, `publish_to_relays`, `run_friend_event_subscription`, `runtime`, `save_friend_avatar_link`, `save_sync_state`, `subscription_generation`, `sync_state_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AvatarBackupPayload`, `BlockedBackupPayload`, `ChatStartedBackupPayload`, `ConfigBackupPayload`, `FriendPayload`, `FriendsBackupPayload`, `IncomingBackupPayload`, `InvitesBackupPayload`, `OutgoingBackupPayload`, `ReadStateBackupPayload`, `RelaysBackupPayload`, `TextBackupPayload`, `Watch`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`

/// Encrypts the given account text (NIP-44, to self) and publishes it as a
/// kind-30078 parameterized-replaceable event, signed with the Nostr keys
/// derived from `mnemonic` (NIP-06). The seed phrase itself is never
/// transmitted — only the deterministically-derived public identity and
/// the encrypted payload.
Future<void> publishAccountBackup({
  required String mnemonic,
  required List<String> relayUrls,
  required String displayName,
  required String statusMessage,
  required PlatformInt64 updatedAt,
}) => RustLib.instance.api.crateApiSyncPublishAccountBackup(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
  displayName: displayName,
  statusMessage: statusMessage,
  updatedAt: updatedAt,
);

/// Fetches and decrypts the newest account text backup for `mnemonic`'s
/// derived identity across `relay_urls`. Returns `None` if no relay has
/// one yet.
Future<RemoteAccount?> fetchAccountBackup({
  required String mnemonic,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiSyncFetchAccountBackup(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
);

/// Publishes the account avatar as its own backup slot — call only when
/// the avatar actually changed, so it isn't re-sent alongside every text
/// edit. `avatar_link` is the encrypted link from
/// `account::upload_account_avatar_link`, not raw image bytes — this slot's
/// content stays small (a URL + hex key) regardless of avatar size.
Future<void> publishAccountAvatarBackup({
  required String mnemonic,
  required List<String> relayUrls,
  required String avatarLink,
  required PlatformInt64 updatedAt,
}) => RustLib.instance.api.crateApiSyncPublishAccountAvatarBackup(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
  avatarLink: avatarLink,
  updatedAt: updatedAt,
);

Future<RemoteAvatar?> fetchAccountAvatarBackup({
  required String mnemonic,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiSyncFetchAccountAvatarBackup(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
);

/// Publishes the account's relay list as its own backup slot — so
/// restoring on another device can pick up the full relay list instead of
/// requiring it to be re-entered by hand.
Future<void> publishAccountRelaysBackup({
  required String mnemonic,
  required List<String> relayUrls,
  required List<String> relays,
  required PlatformInt64 updatedAt,
}) => RustLib.instance.api.crateApiSyncPublishAccountRelaysBackup(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
  relays: relays,
  updatedAt: updatedAt,
);

Future<RemoteRelays?> fetchAccountRelaysBackup({
  required String mnemonic,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiSyncFetchAccountRelaysBackup(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
);

/// Publishes the local friends list (pubkey/account-index/display info,
/// no avatars) as its own backup slot. Call after any change to the
/// friends list (add, accept, favorite, block, delete) so another device
/// can reconstruct the same per-relationship keys and — since chat history
/// is just each device independently pulling and unwrapping the Gift Wraps
/// addressed to those keys — pick up existing conversations too.
Future<void> publishAccountFriendsBackup({
  required String mnemonic,
  required String storageDir,
  required List<String> relayUrls,
  required PlatformInt64 updatedAt,
}) => RustLib.instance.api.crateApiSyncPublishAccountFriendsBackup(
  mnemonic: mnemonic,
  storageDir: storageDir,
  relayUrls: relayUrls,
  updatedAt: updatedAt,
);

Future<RemoteFriends?> fetchAccountFriendsBackup({
  required String mnemonic,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiSyncFetchAccountFriendsBackup(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
);

/// Publishes the blocked-pubkey list as its own backup slot — call after
/// [friends::block_pubkey]/[friends::unblock_pubkey] so a block (or
/// unblock) takes effect on every device signed into this account, not
/// just the one it was done on.
Future<void> publishAccountBlockedBackup({
  required String mnemonic,
  required String storageDir,
  required List<String> relayUrls,
  required PlatformInt64 updatedAt,
}) => RustLib.instance.api.crateApiSyncPublishAccountBlockedBackup(
  mnemonic: mnemonic,
  storageDir: storageDir,
  relayUrls: relayUrls,
  updatedAt: updatedAt,
);

/// Publishes the invite list (and the shared `account` index counter) as
/// its own backup slot — call after creating/revoking an invite, so a QR
/// code shown from any device is recognized (and correctly tracks
/// use-count/revocation) from every device.
Future<void> publishAccountInvitesBackup({
  required String mnemonic,
  required String storageDir,
  required List<String> relayUrls,
  required PlatformInt64 updatedAt,
}) => RustLib.instance.api.crateApiSyncPublishAccountInvitesBackup(
  mnemonic: mnemonic,
  storageDir: storageDir,
  relayUrls: relayUrls,
  updatedAt: updatedAt,
);

/// Publishes the chat read-state map (friend pubkey -> last-read
/// timestamp) as its own backup slot — call after [chat::mark_thread_read]
/// so unread counts stay consistent across devices instead of a thread
/// read on one device still showing unread on another.
Future<void> publishAccountReadstateBackup({
  required String mnemonic,
  required String storageDir,
  required List<String> relayUrls,
  required PlatformInt64 updatedAt,
}) => RustLib.instance.api.crateApiSyncPublishAccountReadstateBackup(
  mnemonic: mnemonic,
  storageDir: storageDir,
  relayUrls: relayUrls,
  updatedAt: updatedAt,
);

/// Publishes personal app preferences (e.g. language) as their own backup
/// slot — call after changing them, so the choice follows this account to
/// every device instead of resetting to "follow device locale" on each
/// one. Never included in any friend-facing payload.
Future<void> publishAccountConfigBackup({
  required String mnemonic,
  required String storageDir,
  required List<String> relayUrls,
  required PlatformInt64 updatedAt,
}) => RustLib.instance.api.crateApiSyncPublishAccountConfigBackup(
  mnemonic: mnemonic,
  storageDir: storageDir,
  relayUrls: relayUrls,
  updatedAt: updatedAt,
);

/// Publishes the set of friends whose chat thread has been explicitly
/// started as its own backup slot — call after [chat::mark_chat_started],
/// so a thread started on one device shows up in the Talk tab on every
/// device signed into this account.
Future<void> publishAccountChatstartedBackup({
  required String mnemonic,
  required String storageDir,
  required List<String> relayUrls,
  required PlatformInt64 updatedAt,
}) => RustLib.instance.api.crateApiSyncPublishAccountChatstartedBackup(
  mnemonic: mnemonic,
  storageDir: storageDir,
  relayUrls: relayUrls,
  updatedAt: updatedAt,
);

/// Requests relays to erase every one of this account's backup slots
/// (NIP-09 deletion request). A no-op per-slot if that slot was never
/// published.
Future<void> deleteAccountBackup({
  required String mnemonic,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiSyncDeleteAccountBackup(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
);

/// Builds the QR payload (as JSON) for the given invite's account index.
Future<String> buildInviteQrPayload({
  required String mnemonic,
  required String storageDir,
  required int accountIndex,
}) => RustLib.instance.api.crateApiSyncBuildInviteQrPayload(
  mnemonic: mnemonic,
  storageDir: storageDir,
  accountIndex: accountIndex,
);

/// Parses a scanned QR's JSON payload back into its fields.
Future<InviteQrPayload> parseInviteQrPayload({required String data}) =>
    RustLib.instance.api.crateApiSyncParseInviteQrPayload(data: data);

/// Sends a friend request to whichever invite `invite_pubkey`/`invite_relays`
/// (scanned from someone's QR code) describe. Mints a fresh per-relationship
/// key for this contact — distinct from our account identity and every
/// other friend's key — and remembers where to look for their acceptance.
Future<void> sendFriendRequest({
  required String mnemonic,
  required String storageDir,
  required String invitePubkey,
  required List<String> inviteRelays,
}) => RustLib.instance.api.crateApiSyncSendFriendRequest(
  mnemonic: mnemonic,
  storageDir: storageDir,
  invitePubkey: invitePubkey,
  inviteRelays: inviteRelays,
);

/// Reads pending incoming friend requests from local storage — persisted
/// as they arrive over the live subscription (see `listen_for_friend_events`),
/// so this never needs to touch a relay. Already-known friends and blocked
/// pubkeys are filtered out (in case a request lingered from before a
/// block/add happened elsewhere).
Future<List<PendingFriendRequest>> loadPendingFriendRequests({
  required String storageDir,
}) => RustLib.instance.api.crateApiSyncLoadPendingFriendRequests(
  storageDir: storageDir,
);

/// Accepts a pending friend request: mints a fresh per-relationship key,
/// tells the requester about it (encrypted to their contact pubkey,
/// published to their relays), and saves them locally as a friend.
///
/// Returns `true` if the requester's UID matched an existing friend (they
/// re-friended us under a new relationship key) — that old entry was
/// merged into this one rather than creating a duplicate, so the caller
/// can tell the user "already a friend, info updated".
Future<bool> acceptFriendRequest({
  required String mnemonic,
  required String storageDir,
  required int inviteAccountIndex,
  required String requesterPubkey,
  required String requesterUid,
  required String requesterDisplayName,
  required String requesterStatusMessage,
  required List<String> requesterRelays,
  String? requesterAvatarLink,
}) => RustLib.instance.api.crateApiSyncAcceptFriendRequest(
  mnemonic: mnemonic,
  storageDir: storageDir,
  inviteAccountIndex: inviteAccountIndex,
  requesterPubkey: requesterPubkey,
  requesterUid: requesterUid,
  requesterDisplayName: requesterDisplayName,
  requesterStatusMessage: requesterStatusMessage,
  requesterRelays: requesterRelays,
  requesterAvatarLink: requesterAvatarLink,
);

/// Permanently blocks a requester's contact pubkey so their (rejected)
/// friend request stops showing up, even if resent.
Future<void> rejectFriendRequest({
  required String mnemonic,
  required String storageDir,
  required List<String> relayUrls,
  required String requesterPubkey,
}) => RustLib.instance.api.crateApiSyncRejectFriendRequest(
  mnemonic: mnemonic,
  storageDir: storageDir,
  relayUrls: relayUrls,
  requesterPubkey: requesterPubkey,
);

/// Publishes the given profile info to every existing friend, each using
/// the per-relationship key already established for them, encrypted to
/// their contact pubkey, and sent to their last-known relays. Every such
/// event carries our current relay list too, so friends always pick up
/// our latest relays as a side effect of any update reaching them — no
/// separate relay-discovery mechanism needed. `avatar_link` should be
/// `None` when only the text fields changed, to avoid re-sending it (still
/// small, but no need) on every edit.
Future<void> publishProfileUpdateToFriends({
  required String mnemonic,
  required String storageDir,
  required String displayName,
  required String statusMessage,
  String? avatarLink,
}) => RustLib.instance.api.crateApiSyncPublishProfileUpdateToFriends(
  mnemonic: mnemonic,
  storageDir: storageDir,
  displayName: displayName,
  statusMessage: statusMessage,
  avatarLink: avatarLink,
);

/// Opens a connection to this account's relays (plus any outstanding
/// outgoing requests' relays) and streams friend-request / friend-accept
/// events as they arrive, for as long as the returned Dart stream is
/// listened to. Reflects the set of invites/requests that existed at the
/// moment this was called — call again (the Dart side cancels the old
/// subscription first) after creating a new invite or sending a request.
Stream<FriendEvent> subscribeFriendEvents({
  required String mnemonic,
  required String storageDir,
  String? ratchetKey,
}) => RustLib.instance.api.crateApiSyncSubscribeFriendEvents(
  mnemonic: mnemonic,
  storageDir: storageDir,
  ratchetKey: ratchetKey,
);

/// One friend as carried in the friends-list backup — enough for another
/// device to derive the same per-relationship key (`my_account_index`) and
/// resume talking to (and pulling chat history for) this friend on its
/// own. Deliberately excludes the avatar (each device re-caches it from
/// the friend directly, the same way it originally arrived).
class FriendBackupEntry {
  final String pubkey;
  final String uid;
  final int myAccountIndex;
  final String displayName;
  final String statusMessage;
  final List<String> relays;
  final bool isFavorite;

  const FriendBackupEntry({
    required this.pubkey,
    required this.uid,
    required this.myAccountIndex,
    required this.displayName,
    required this.statusMessage,
    required this.relays,
    required this.isFavorite,
  });

  @override
  int get hashCode =>
      pubkey.hashCode ^
      uid.hashCode ^
      myAccountIndex.hashCode ^
      displayName.hashCode ^
      statusMessage.hashCode ^
      relays.hashCode ^
      isFavorite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendBackupEntry &&
          runtimeType == other.runtimeType &&
          pubkey == other.pubkey &&
          uid == other.uid &&
          myAccountIndex == other.myAccountIndex &&
          displayName == other.displayName &&
          statusMessage == other.statusMessage &&
          relays == other.relays &&
          isFavorite == other.isFavorite;
}

/// A live update about a friend request or acceptance, delivered while
/// this device stays connected to its relays. Cheaper than re-polling: the
/// connection just sits idle (a few bytes of keepalive) until a relay
/// actually has something to send.
class FriendEvent {
  /// `"request"`, `"accepted"`, `"profile_updated"`, `"message"`, or
  /// `"account_synced"` (a newer copy of our own text/avatar/relays/
  /// friends backup arrived from another device and was applied locally).
  /// `"reconnecting"` is also sent (and safely ignorable) each time a
  /// relay connection drops and this subscription is about to retry it.
  final String kind;
  final String pubkey;
  final String displayName;
  final String statusMessage;

  /// Only set for `"request"` — which invite it arrived on, needed to
  /// accept it.
  final int? inviteAccountIndex;

  /// Only set for `"request"` — the requester's relays, needed to accept it.
  final List<String> relays;

  /// Only set for `"message"` — the decrypted chat message text.
  final String? content;

  const FriendEvent({
    required this.kind,
    required this.pubkey,
    required this.displayName,
    required this.statusMessage,
    this.inviteAccountIndex,
    required this.relays,
    this.content,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      pubkey.hashCode ^
      displayName.hashCode ^
      statusMessage.hashCode ^
      inviteAccountIndex.hashCode ^
      relays.hashCode ^
      content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          pubkey == other.pubkey &&
          displayName == other.displayName &&
          statusMessage == other.statusMessage &&
          inviteAccountIndex == other.inviteAccountIndex &&
          relays == other.relays &&
          content == other.content;
}

/// The data a "my QR" screen encodes: enough for a scanner to send a
/// friend request without any prior relay round-trip. Shown in person, so
/// including the display name/status here isn't a public disclosure the
/// way publishing them to a relay would be.
class InviteQrPayload {
  final String pubkey;
  final List<String> relays;
  final String displayName;
  final String statusMessage;

  /// The inviter's stable account UID (see `keys::derive_uid`). Lets a
  /// scanner recognize "I already have this account as a friend" right
  /// at scan time — before sending a request and waiting for an accept
  /// round-trip — even though `pubkey` above is a fresh per-invite key
  /// that won't match any existing friend entry.
  final String uid;

  const InviteQrPayload({
    required this.pubkey,
    required this.relays,
    required this.displayName,
    required this.statusMessage,
    required this.uid,
  });

  @override
  int get hashCode =>
      pubkey.hashCode ^
      relays.hashCode ^
      displayName.hashCode ^
      statusMessage.hashCode ^
      uid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InviteQrPayload &&
          runtimeType == other.runtimeType &&
          pubkey == other.pubkey &&
          relays == other.relays &&
          displayName == other.displayName &&
          statusMessage == other.statusMessage &&
          uid == other.uid;
}

/// A pending incoming friend request, decrypted and ready to show the user.
class PendingFriendRequest {
  /// Which of our invites this request was sent to.
  final int inviteAccountIndex;

  /// The requester's contact pubkey (hex) — distinct per relationship.
  final String pubkey;

  /// The requester's stable account UID (see `keys::derive_uid`).
  final String uid;
  final String displayName;
  final String statusMessage;
  final List<String> relays;

  /// Encrypted avatar link, if the requester has one — passed through
  /// unchanged so `accept_friend_request` can download/cache it.
  final String? avatarLink;

  const PendingFriendRequest({
    required this.inviteAccountIndex,
    required this.pubkey,
    required this.uid,
    required this.displayName,
    required this.statusMessage,
    required this.relays,
    this.avatarLink,
  });

  @override
  int get hashCode =>
      inviteAccountIndex.hashCode ^
      pubkey.hashCode ^
      uid.hashCode ^
      displayName.hashCode ^
      statusMessage.hashCode ^
      relays.hashCode ^
      avatarLink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingFriendRequest &&
          runtimeType == other.runtimeType &&
          inviteAccountIndex == other.inviteAccountIndex &&
          pubkey == other.pubkey &&
          uid == other.uid &&
          displayName == other.displayName &&
          statusMessage == other.statusMessage &&
          relays == other.relays &&
          avatarLink == other.avatarLink;
}

/// Account text (display name / status) decrypted from a relay-hosted backup.
class RemoteAccount {
  final String displayName;
  final String statusMessage;
  final PlatformInt64 updatedAt;

  const RemoteAccount({
    required this.displayName,
    required this.statusMessage,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^ statusMessage.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteAccount &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          statusMessage == other.statusMessage &&
          updatedAt == other.updatedAt;
}

class RemoteAvatar {
  final String avatarLink;
  final PlatformInt64 updatedAt;

  const RemoteAvatar({required this.avatarLink, required this.updatedAt});

  @override
  int get hashCode => avatarLink.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteAvatar &&
          runtimeType == other.runtimeType &&
          avatarLink == other.avatarLink &&
          updatedAt == other.updatedAt;
}

class RemoteFriends {
  final List<FriendBackupEntry> friends;
  final PlatformInt64 updatedAt;

  const RemoteFriends({required this.friends, required this.updatedAt});

  @override
  int get hashCode => friends.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteFriends &&
          runtimeType == other.runtimeType &&
          friends == other.friends &&
          updatedAt == other.updatedAt;
}

class RemoteRelays {
  final List<String> relays;
  final PlatformInt64 updatedAt;

  const RemoteRelays({required this.relays, required this.updatedAt});

  @override
  int get hashCode => relays.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteRelays &&
          runtimeType == other.runtimeType &&
          relays == other.relays &&
          updatedAt == other.updatedAt;
}

/// Tracks the `updated_at` of the last-applied avatar/relays/friends backup
/// per storage dir, so [listen_for_account_sync] can reject stale or
/// duplicate events by timestamp rather than by content — content-equality
/// alone isn't enough: an older event arriving after a newer one (relays
/// don't guarantee delivery order across each other, and this filter has no
/// `since` so a fresh subscription replays whatever each individual relay
/// currently has) would otherwise overwrite the newer local state right
/// back to the older content. The text backup already tracks this via
/// `Account.updated_at`; this covers the other three slots, which have no
/// existing local timestamp field of their own to compare against.
class SyncState {
  final PlatformInt64 avatarUpdatedAt;
  final PlatformInt64 relaysUpdatedAt;
  final PlatformInt64 friendsUpdatedAt;
  final PlatformInt64 blockedUpdatedAt;
  final PlatformInt64 invitesUpdatedAt;
  final PlatformInt64 outgoingUpdatedAt;
  final PlatformInt64 incomingUpdatedAt;
  final PlatformInt64 readstateUpdatedAt;
  final PlatformInt64 configUpdatedAt;
  final PlatformInt64 chatstartedUpdatedAt;

  /// `created_at` of the newest friend-protocol/chat event this device has
  /// successfully processed, across every relay — used as `since` when
  /// (re)subscribing in [run_friend_event_subscription] so a reconnect (app
  /// relaunch, network drop) only asks relays to redeliver what's newer
  /// than this, instead of replaying the account's entire history every
  /// time. Only advanced on confirmed-successful processing (see call
  /// sites in [listen_for_friend_events]), never on a bare decode attempt,
  /// so a transient failure (e.g. a friend's key material not loaded into
  /// `watch` yet) stays eligible for redelivery on the next resubscribe.
  final PlatformInt64 friendEventsSince;

  const SyncState({
    required this.avatarUpdatedAt,
    required this.relaysUpdatedAt,
    required this.friendsUpdatedAt,
    required this.blockedUpdatedAt,
    required this.invitesUpdatedAt,
    required this.outgoingUpdatedAt,
    required this.incomingUpdatedAt,
    required this.readstateUpdatedAt,
    required this.configUpdatedAt,
    required this.chatstartedUpdatedAt,
    required this.friendEventsSince,
  });

  static Future<SyncState> default_() =>
      RustLib.instance.api.crateApiSyncSyncStateDefault();

  @override
  int get hashCode =>
      avatarUpdatedAt.hashCode ^
      relaysUpdatedAt.hashCode ^
      friendsUpdatedAt.hashCode ^
      blockedUpdatedAt.hashCode ^
      invitesUpdatedAt.hashCode ^
      outgoingUpdatedAt.hashCode ^
      incomingUpdatedAt.hashCode ^
      readstateUpdatedAt.hashCode ^
      configUpdatedAt.hashCode ^
      chatstartedUpdatedAt.hashCode ^
      friendEventsSince.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncState &&
          runtimeType == other.runtimeType &&
          avatarUpdatedAt == other.avatarUpdatedAt &&
          relaysUpdatedAt == other.relaysUpdatedAt &&
          friendsUpdatedAt == other.friendsUpdatedAt &&
          blockedUpdatedAt == other.blockedUpdatedAt &&
          invitesUpdatedAt == other.invitesUpdatedAt &&
          outgoingUpdatedAt == other.outgoingUpdatedAt &&
          incomingUpdatedAt == other.incomingUpdatedAt &&
          readstateUpdatedAt == other.readstateUpdatedAt &&
          configUpdatedAt == other.configUpdatedAt &&
          chatstartedUpdatedAt == other.chatstartedUpdatedAt &&
          friendEventsSince == other.friendEventsSince;
}
